### ISSUE TITLE
come up with a better title for this tutorial

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/web-tutorial#61]
and rename this repository to match

**Comment by gvwilson** [comment]
1. Change the repo to `web-tutorial` to match [`sql-tutorial`](https://github.com/gvwilson/sql-tutorial) and [`sys-tutorial`](https://github.com/gvwilson/sys-tutorial).
2. Change the title to `Webonomicon` to match their titles `Querynomicon` and `Sudonomicon`.

(H.P. Lovecraft's horror stories featured a book of dark knowledge called the *Necronomicon*. That inspired me to call the SQL tutorial the "Querynomicon", which in turn inspired the idea of "sudo-nomicon" for the systems programming tutorial.)

**Comment by juananpe** [comment]
> `web-tutorial` for the repo, `Webonomicon` for the title. 
> (H.P. Lovecraft's horror stories featured a book of dark knowledge called the _Necronomicon_. That inspired me to call the SQL tutorial the "Querynomicon", which in turn inspired the idea of "sudo-nomicon" for the systems programming tutorial.)

Great choice. The Necronomicon is described as a book of arcane knowledge and ritual magic, just like SQL, Unix, and Web development :)
